[project]
name = "t01-modern-project-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "swork3091-jpg", email = "swork3091@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
t01-modern-project-setup = "t01_modern_project_setup:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
